title: "MyTravis Spec Runner"
js:
  - js/lib/o.min.js
  - js/lib/jquery-1.9.1.min.js
  - js/lib/utils.src.js
  - specs/matchers.js

  - js/app.src.js
  - js/controller/list.src.js
  - js/controller/notification.src.js
  - js/model/projs.src.js
  - js/model/prefs.src.js
  - js/badge.src.js

  - specs/lib/utils.spec.js
  - specs/controller/controller.spec.js
  - specs/controller/list.spec.js
  - specs/controller/notification.spec.js
  - specs/model/model.spec.js
  - specs/model/projs.spec.js
  - specs/model/prefs.spec.js
  - specs/badge.spec.js
