title: "MyTravis Spec Runner"
css:
  - spec/spec.src.css
js:
  - js/lib/o.min.js
  - js/lib/litemq.min.js
  - js/lib/jquery-1.9.1.min.js
  - js/lib/utils.src.js
  - spec/spec.src.js

  - js/app.src.js
  - js/controller/analytics.src.js
  - js/controller/header.src.js
  - js/controller/form.src.js
  - js/controller/list.src.js
  - js/controller/notification.src.js
  - js/model/projs.src.js
  - js/model/prefs.src.js
  - js/model/travis.src.js
  - js/service/updater.src.js
  - js/badge.src.js

  - spec/lib/utils.spec.js
  - spec/controller/controller.spec.js
  - spec/controller/analytics.spec.js
  - spec/controller/header.spec.js
  - spec/controller/form.spec.js
  - spec/controller/list.spec.js
  - spec/controller/notification.spec.js
  - spec/model/model.spec.js
  - spec/model/projs.spec.js
  - spec/model/prefs.spec.js
  - spec/model/travis.spec.js
  - spec/service/updater.spec.js
  - spec/badge.spec.js
